import type { Movie, Review } from '../types';

export const MOCK_MOVIES: Movie[] = [
  {
    id: 1,
    title: 'Inception',
    year: 2010,
    genre: ['Sci-Fi', 'Action', 'Thriller'],
    overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    director: 'Christopher Nolan',
    cast: [
      { id: 1, name: 'Leonardo DiCaprio', character: 'Cobb' },
      { id: 2, name: 'Joseph Gordon-Levitt', character: 'Arthur' },
      { id: 3, name: 'Ellen Page', character: 'Ariadne' },
      { id: 4, name: 'Tom Hardy', character: 'Eames' },
    ],
    runtime: 148,
    language: 'English',
    country: 'USA',
    imdbRating: 8.8,
    rottenTomatoes: 87,
    posterColor: 'linear-gradient(145deg, #0f2027, #203a43, #2c5364)',
    accentColor: '#4FC3F7',
    backdropColor: 'linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)',
    status: 'watched',
    userRating: 9,
    watchedDate: '2024-03-15',
    isFavorite: true,
    isInWatchlist: false,
    decade: 2010,
    popularity: 98,
    awards: ['Academy Award for Best Cinematography', 'Best Visual Effects'],
    budget: 160000000,
    boxOffice: 836800000,
    streamingOn: ['Netflix', 'HBO Max'],
  },
  {
    id: 2,
    title: 'The Dark Knight',
    year: 2008,
    genre: ['Action', 'Crime', 'Drama'],
    overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    director: 'Christopher Nolan',
    cast: [
      { id: 5, name: 'Christian Bale', character: 'Batman' },
      { id: 6, name: 'Heath Ledger', character: 'Joker' },
      { id: 7, name: 'Gary Oldman', character: 'Gordon' },
      { id: 8, name: 'Aaron Eckhart', character: 'Harvey Dent' },
    ],
    runtime: 152,
    language: 'English',
    country: 'USA',
    imdbRating: 9.0,
    rottenTomatoes: 94,
    posterColor: 'linear-gradient(145deg, #0a0a0a, #1a1a2e, #16213e)',
    accentColor: '#FFD700',
    backdropColor: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a2e 50%, #16213e 100%)',
    status: 'watched',
    userRating: 10,
    watchedDate: '2024-02-10',
    isFavorite: true,
    isInWatchlist: false,
    decade: 2000,
    popularity: 99,
    awards: ['Academy Award for Best Supporting Actor (Heath Ledger)'],
    budget: 185000000,
    boxOffice: 1005000000,
    streamingOn: ['HBO Max'],
  },
  {
    id: 3,
    title: 'Interstellar',
    year: 2014,
    genre: ['Sci-Fi', 'Drama', 'Adventure'],
    overview: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    director: 'Christopher Nolan',
    cast: [
      { id: 9, name: 'Matthew McConaughey', character: 'Cooper' },
      { id: 10, name: 'Anne Hathaway', character: 'Brand' },
      { id: 11, name: 'Jessica Chastain', character: 'Murph' },
    ],
    runtime: 169,
    language: 'English',
    country: 'USA',
    imdbRating: 8.7,
    rottenTomatoes: 73,
    posterColor: 'linear-gradient(145deg, #000428, #004e92, #1a1a2e)',
    accentColor: '#F97316',
    backdropColor: 'linear-gradient(135deg, #000428 0%, #004e92 50%, #0a0a0a 100%)',
    status: 'watched',
    userRating: 9,
    watchedDate: '2024-01-20',
    isFavorite: true,
    isInWatchlist: false,
    decade: 2010,
    popularity: 96,
    awards: ['Academy Award for Best Visual Effects'],
    budget: 165000000,
    boxOffice: 773000000,
    streamingOn: ['Paramount+'],
  },
  {
    id: 4,
    title: 'Parasite',
    year: 2019,
    genre: ['Thriller', 'Drama', 'Comedy'],
    overview: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    director: 'Bong Joon-ho',
    cast: [
      { id: 12, name: 'Song Kang-ho', character: 'Ki-taek' },
      { id: 13, name: 'Lee Sun-kyun', character: 'Park Dong-ik' },
      { id: 14, name: 'Cho Yeo-jeong', character: 'Choi Yeon-gyo' },
    ],
    runtime: 132,
    language: 'Korean',
    country: 'South Korea',
    imdbRating: 8.5,
    rottenTomatoes: 99,
    posterColor: 'linear-gradient(145deg, #1a1a2e, #16213e, #0f3460)',
    accentColor: '#22C55E',
    backdropColor: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
    status: 'watched',
    userRating: 8,
    watchedDate: '2024-04-05',
    isFavorite: false,
    isInWatchlist: false,
    decade: 2010,
    popularity: 95,
    awards: ['Academy Award for Best Picture', 'Best Director', 'Best Original Screenplay', 'Best International Film'],
    budget: 11400000,
    boxOffice: 258900000,
    streamingOn: ['Hulu'],
  },
  {
    id: 5,
    title: 'The Shawshank Redemption',
    year: 1994,
    genre: ['Drama'],
    overview: 'Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.',
    director: 'Frank Darabont',
    cast: [
      { id: 15, name: 'Tim Robbins', character: 'Andy Dufresne' },
      { id: 16, name: 'Morgan Freeman', character: 'Ellis Boyd "Red" Redding' },
    ],
    runtime: 142,
    language: 'English',
    country: 'USA',
    imdbRating: 9.3,
    rottenTomatoes: 91,
    posterColor: 'linear-gradient(145deg, #2c1810, #5c3317, #8b4513)',
    accentColor: '#F59E0B',
    backdropColor: 'linear-gradient(135deg, #2c1810 0%, #5c3317 50%, #8b4513 100%)',
    status: 'watched',
    userRating: 10,
    watchedDate: '2023-12-25',
    isFavorite: true,
    isInWatchlist: false,
    decade: 1990,
    popularity: 100,
    budget: 25000000,
    boxOffice: 16000000,
    streamingOn: ['Netflix'],
  },
  {
    id: 6,
    title: 'Dune',
    year: 2021,
    genre: ['Sci-Fi', 'Adventure', 'Drama'],
    overview: "Feature adaptation of Frank Herbert's science fiction novel about the son of a noble family entrusted with the protection of the most valuable asset and most vital element in the galaxy.",
    director: 'Denis Villeneuve',
    cast: [
      { id: 17, name: 'Timothée Chalamet', character: 'Paul Atreides' },
      { id: 18, name: 'Rebecca Ferguson', character: 'Lady Jessica' },
      { id: 19, name: 'Oscar Isaac', character: 'Duke Leto Atreides' },
      { id: 20, name: 'Zendaya', character: 'Chani' },
    ],
    runtime: 155,
    language: 'English',
    country: 'USA',
    imdbRating: 8.0,
    rottenTomatoes: 83,
    posterColor: 'linear-gradient(145deg, #8B4513, #D2691E, #F4A460)',
    accentColor: '#F59E0B',
    backdropColor: 'linear-gradient(135deg, #8B4513 0%, #D2691E 50%, #C19A6B 100%)',
    status: 'watched',
    userRating: 8,
    watchedDate: '2024-05-12',
    isFavorite: false,
    isInWatchlist: false,
    decade: 2020,
    popularity: 92,
    awards: ['Academy Award for Best Cinematography', 'Best Film Editing'],
    budget: 165000000,
    boxOffice: 402000000,
    streamingOn: ['HBO Max'],
  },
  {
    id: 7,
    title: 'The Godfather',
    year: 1972,
    genre: ['Crime', 'Drama'],
    overview: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    director: 'Francis Ford Coppola',
    cast: [
      { id: 21, name: 'Marlon Brando', character: 'Don Vito Corleone' },
      { id: 22, name: 'Al Pacino', character: 'Michael Corleone' },
      { id: 23, name: 'James Caan', character: 'Sonny Corleone' },
    ],
    runtime: 175,
    language: 'English',
    country: 'USA',
    imdbRating: 9.2,
    rottenTomatoes: 97,
    posterColor: 'linear-gradient(145deg, #1a0a00, #3d1c00, #6b3a2a)',
    accentColor: '#C9A227',
    backdropColor: 'linear-gradient(135deg, #1a0a00 0%, #3d1c00 50%, #6b3a2a 100%)',
    status: 'watched',
    userRating: 10,
    watchedDate: '2024-01-05',
    isFavorite: true,
    isInWatchlist: false,
    decade: 1970,
    popularity: 99,
    awards: ['Academy Award for Best Picture', 'Best Actor', 'Best Adapted Screenplay'],
    budget: 6000000,
    boxOffice: 245066000,
    streamingOn: ['Paramount+'],
  },
  {
    id: 8,
    title: 'Blade Runner 2049',
    year: 2017,
    genre: ['Sci-Fi', 'Drama', 'Mystery'],
    overview: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    director: 'Denis Villeneuve',
    cast: [
      { id: 24, name: 'Ryan Gosling', character: 'K' },
      { id: 25, name: 'Harrison Ford', character: 'Rick Deckard' },
      { id: 26, name: 'Ana de Armas', character: 'Joi' },
    ],
    runtime: 164,
    language: 'English',
    country: 'USA',
    imdbRating: 8.0,
    rottenTomatoes: 88,
    posterColor: 'linear-gradient(145deg, #0d0d1a, #1a1a3e, #2d2d6b)',
    accentColor: '#F97316',
    backdropColor: 'linear-gradient(135deg, #0d0d1a 0%, #1a1a3e 50%, #2d2d6b 100%)',
    status: 'watched',
    userRating: 9,
    watchedDate: '2024-02-28',
    isFavorite: true,
    isInWatchlist: false,
    decade: 2010,
    popularity: 87,
    awards: ['Academy Award for Best Cinematography', 'Best Visual Effects'],
    budget: 150000000,
    boxOffice: 259200000,
    streamingOn: ['Amazon Prime'],
  },
  {
    id: 9,
    title: 'Whiplash',
    year: 2014,
    genre: ['Drama', 'Music'],
    overview: 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential.',
    director: 'Damien Chazelle',
    cast: [
      { id: 27, name: 'Miles Teller', character: 'Andrew Neiman' },
      { id: 28, name: 'J.K. Simmons', character: 'Terence Fletcher' },
    ],
    runtime: 107,
    language: 'English',
    country: 'USA',
    imdbRating: 8.5,
    rottenTomatoes: 94,
    posterColor: 'linear-gradient(145deg, #1a0000, #3d0000, #800000)',
    accentColor: '#EF4444',
    backdropColor: 'linear-gradient(135deg, #1a0000 0%, #3d0000 50%, #800000 100%)',
    status: 'watched',
    userRating: 9,
    watchedDate: '2024-06-01',
    isFavorite: true,
    isInWatchlist: false,
    decade: 2010,
    popularity: 90,
    awards: ['Academy Award for Best Supporting Actor', 'Best Film Editing', 'Best Sound Mixing'],
    budget: 3300000,
    boxOffice: 49000000,
    streamingOn: ['Netflix'],
  },
  {
    id: 10,
    title: 'La La Land',
    year: 2016,
    genre: ['Drama', 'Music', 'Romance'],
    overview: 'While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.',
    director: 'Damien Chazelle',
    cast: [
      { id: 29, name: 'Ryan Gosling', character: 'Sebastian' },
      { id: 30, name: 'Emma Stone', character: 'Mia' },
    ],
    runtime: 128,
    language: 'English',
    country: 'USA',
    imdbRating: 8.0,
    rottenTomatoes: 91,
    posterColor: 'linear-gradient(145deg, #1a0d2e, #2d1b69, #7c3aed)',
    accentColor: '#A78BFA',
    backdropColor: 'linear-gradient(135deg, #1a0d2e 0%, #2d1b69 50%, #4c1d95 100%)',
    status: 'watched',
    userRating: 8,
    watchedDate: '2024-03-22',
    isFavorite: false,
    isInWatchlist: false,
    decade: 2010,
    popularity: 88,
    awards: ['Academy Award for Best Director', 'Best Actress', 'Best Cinematography'],
    budget: 30000000,
    boxOffice: 448900000,
    streamingOn: ['Netflix'],
  },
  {
    id: 11,
    title: 'Oppenheimer',
    year: 2023,
    genre: ['Drama', 'History', 'Biography'],
    overview: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.',
    director: 'Christopher Nolan',
    cast: [
      { id: 31, name: 'Cillian Murphy', character: 'J. Robert Oppenheimer' },
      { id: 32, name: 'Emily Blunt', character: 'Katherine "Kitty" Oppenheimer' },
      { id: 33, name: 'Matt Damon', character: 'Leslie Groves' },
      { id: 34, name: 'Robert Downey Jr.', character: 'Lewis Strauss' },
    ],
    runtime: 180,
    language: 'English',
    country: 'USA',
    imdbRating: 8.3,
    rottenTomatoes: 93,
    posterColor: 'linear-gradient(145deg, #1a0a00, #4a1a00, #8b3000)',
    accentColor: '#F97316',
    backdropColor: 'linear-gradient(135deg, #1a0a00 0%, #4a1a00 50%, #8b3000 100%)',
    status: 'watched',
    userRating: 9,
    watchedDate: '2023-08-01',
    isFavorite: true,
    isInWatchlist: false,
    decade: 2020,
    popularity: 97,
    awards: ['Academy Award for Best Picture', 'Best Director', 'Best Actor'],
    budget: 100000000,
    boxOffice: 952000000,
    streamingOn: ['Peacock'],
  },
  {
    id: 12,
    title: 'Everything Everywhere All at Once',
    year: 2022,
    genre: ['Sci-Fi', 'Action', 'Comedy', 'Drama'],
    overview: 'An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what\'s important to her by connecting with the lives she could have led in other universes.',
    director: 'Daniel Kwan & Daniel Scheinert',
    cast: [
      { id: 35, name: 'Michelle Yeoh', character: 'Evelyn Wang' },
      { id: 36, name: 'Ke Huy Quan', character: 'Waymond Wang' },
      { id: 37, name: 'Jamie Lee Curtis', character: 'Deirdre Beaubeirdre' },
    ],
    runtime: 139,
    language: 'English',
    country: 'USA',
    imdbRating: 7.8,
    rottenTomatoes: 95,
    posterColor: 'linear-gradient(145deg, #0f0c29, #302b63, #24243e)',
    accentColor: '#EC4899',
    backdropColor: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
    status: 'watched',
    userRating: 8,
    watchedDate: '2024-05-20',
    isFavorite: false,
    isInWatchlist: false,
    decade: 2020,
    popularity: 88,
    awards: ['Academy Award for Best Picture', 'Best Actress', 'Best Supporting Actor'],
    budget: 14300000,
    boxOffice: 76700000,
    streamingOn: ['Amazon Prime'],
  },
  {
    id: 13,
    title: 'Tár',
    year: 2022,
    genre: ['Drama', 'Music'],
    overview: 'Set in the international world of classical music, the film centers on Lydia Tár, widely considered one of the greatest living composer-conductors and the first-ever female chief conductor of a major German orchestra.',
    director: 'Todd Field',
    cast: [
      { id: 38, name: 'Cate Blanchett', character: 'Lydia Tár' },
      { id: 39, name: 'Nina Hoss', character: 'Sharon Goodnow' },
    ],
    runtime: 158,
    language: 'English',
    country: 'USA',
    imdbRating: 7.4,
    rottenTomatoes: 91,
    posterColor: 'linear-gradient(145deg, #0d0d0d, #1a1a1a, #2d2d2d)',
    accentColor: '#94A3B8',
    backdropColor: 'linear-gradient(135deg, #0d0d0d 0%, #1a1a1a 50%, #2d2d2d 100%)',
    status: 'plan_to_watch',
    isFavorite: false,
    isInWatchlist: true,
    watchlistPriority: 2,
    decade: 2020,
    popularity: 72,
    streamingOn: ['Peacock'],
  },
  {
    id: 14,
    title: 'Aftersun',
    year: 2022,
    genre: ['Drama'],
    overview: 'Sophie reflects on the shared joy and private melancholy of a holiday she took with her father twenty years earlier, as she tries to reconcile the father she knew with the man she didn\'t.',
    director: 'Charlotte Wells',
    cast: [
      { id: 40, name: 'Paul Mescal', character: 'Calum' },
      { id: 41, name: 'Frankie Corio', character: 'Sophie' },
    ],
    runtime: 101,
    language: 'English',
    country: 'UK',
    imdbRating: 7.6,
    rottenTomatoes: 96,
    posterColor: 'linear-gradient(145deg, #0a1628, #1e3a5f, #2563eb)',
    accentColor: '#60A5FA',
    backdropColor: 'linear-gradient(135deg, #0a1628 0%, #1e3a5f 50%, #2563eb 100%)',
    status: 'plan_to_watch',
    isFavorite: false,
    isInWatchlist: true,
    watchlistPriority: 1,
    decade: 2020,
    popularity: 70,
    streamingOn: ['MUBI'],
  },
  {
    id: 15,
    title: 'The Batman',
    year: 2022,
    genre: ['Action', 'Crime', 'Drama'],
    overview: 'When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city\'s hidden corruption and question his family\'s involvement.',
    director: 'Matt Reeves',
    cast: [
      { id: 42, name: 'Robert Pattinson', character: 'Batman / Bruce Wayne' },
      { id: 43, name: 'Zoë Kravitz', character: 'Catwoman / Selina Kyle' },
      { id: 44, name: 'Paul Dano', character: 'The Riddler' },
    ],
    runtime: 176,
    language: 'English',
    country: 'USA',
    imdbRating: 7.8,
    rottenTomatoes: 85,
    posterColor: 'linear-gradient(145deg, #050505, #0f0f1a, #1a1a2e)',
    accentColor: '#60A5FA',
    backdropColor: 'linear-gradient(135deg, #050505 0%, #0f0f1a 50%, #1a1a2e 100%)',
    status: 'watched',
    userRating: 8,
    watchedDate: '2024-04-15',
    isFavorite: false,
    isInWatchlist: false,
    decade: 2020,
    popularity: 86,
    budget: 185000000,
    boxOffice: 770800000,
    streamingOn: ['HBO Max'],
  },
  {
    id: 16,
    title: 'Midsommar',
    year: 2019,
    genre: ['Horror', 'Drama', 'Mystery'],
    overview: 'A couple travels to Sweden to visit a rural hometown\'s fabled midsummer festival. What begins as an idyllic retreat quickly devolves into an increasingly violent and bizarre competition at the hands of a pagan cult.',
    director: 'Ari Aster',
    cast: [
      { id: 45, name: 'Florence Pugh', character: 'Dani' },
      { id: 46, name: 'Jack Reynor', character: 'Christian' },
    ],
    runtime: 148,
    language: 'English',
    country: 'USA',
    imdbRating: 7.1,
    rottenTomatoes: 83,
    posterColor: 'linear-gradient(145deg, #1a3a00, #2d5a00, #4a8c00)',
    accentColor: '#84CC16',
    backdropColor: 'linear-gradient(135deg, #1a3a00 0%, #2d5a00 50%, #4a8c00 100%)',
    status: 'watched',
    userRating: 7,
    watchedDate: '2024-07-01',
    isFavorite: false,
    isInWatchlist: false,
    decade: 2010,
    popularity: 78,
    budget: 9000000,
    boxOffice: 29000000,
    streamingOn: ['Amazon Prime'],
  },
  {
    id: 17,
    title: 'Portrait of a Lady on Fire',
    year: 2019,
    genre: ['Drama', 'Romance'],
    overview: 'On an isolated island in Bretagne at the end of the eighteenth century, a female painter is obliged to paint a wedding portrait of a young woman.',
    director: 'Céline Sciamma',
    cast: [
      { id: 47, name: 'Noémie Merlant', character: 'Marianne' },
      { id: 48, name: 'Adèle Haenel', character: 'Héloïse' },
    ],
    runtime: 122,
    language: 'French',
    country: 'France',
    imdbRating: 8.1,
    rottenTomatoes: 98,
    posterColor: 'linear-gradient(145deg, #1a0d0d, #3d1a1a, #6b2d2d)',
    accentColor: '#F97316',
    backdropColor: 'linear-gradient(135deg, #1a0d0d 0%, #3d1a1a 50%, #6b2d2d 100%)',
    status: 'plan_to_watch',
    isFavorite: false,
    isInWatchlist: true,
    watchlistPriority: 3,
    decade: 2010,
    popularity: 82,
    streamingOn: ['Hulu', 'MUBI'],
  },
  {
    id: 18,
    title: 'Arrival',
    year: 2016,
    genre: ['Sci-Fi', 'Drama', 'Mystery'],
    overview: 'A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.',
    director: 'Denis Villeneuve',
    cast: [
      { id: 49, name: 'Amy Adams', character: 'Louise Banks' },
      { id: 50, name: 'Jeremy Renner', character: 'Ian Donnelly' },
      { id: 51, name: 'Forest Whitaker', character: 'Colonel Weber' },
    ],
    runtime: 116,
    language: 'English',
    country: 'USA',
    imdbRating: 7.9,
    rottenTomatoes: 94,
    posterColor: 'linear-gradient(145deg, #0d1a0d, #1a3a1a, #2d5a2d)',
    accentColor: '#86EFAC',
    backdropColor: 'linear-gradient(135deg, #0d1a0d 0%, #1a3a1a 50%, #2d5a2d 100%)',
    status: 'watched',
    userRating: 8,
    watchedDate: '2024-06-15',
    isFavorite: false,
    isInWatchlist: false,
    decade: 2010,
    popularity: 89,
    budget: 47000000,
    boxOffice: 203000000,
    streamingOn: ['Amazon Prime'],
  },
  {
    id: 19,
    title: 'Her',
    year: 2013,
    genre: ['Sci-Fi', 'Drama', 'Romance'],
    overview: 'In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.',
    director: 'Spike Jonze',
    cast: [
      { id: 52, name: 'Joaquin Phoenix', character: 'Theodore' },
      { id: 53, name: 'Scarlett Johansson', character: 'Samantha (voice)' },
      { id: 54, name: 'Amy Adams', character: 'Amy' },
    ],
    runtime: 126,
    language: 'English',
    country: 'USA',
    imdbRating: 8.0,
    rottenTomatoes: 94,
    posterColor: 'linear-gradient(145deg, #3d0000, #7a0000, #c0392b)',
    accentColor: '#FCA5A5',
    backdropColor: 'linear-gradient(135deg, #3d0000 0%, #7a0000 50%, #c0392b 100%)',
    status: 'watched',
    userRating: 8,
    watchedDate: '2024-03-01',
    isFavorite: true,
    isInWatchlist: false,
    decade: 2010,
    popularity: 85,
    budget: 23000000,
    boxOffice: 48000000,
    streamingOn: ['Netflix'],
  },
  {
    id: 20,
    title: 'The Grand Budapest Hotel',
    year: 2014,
    genre: ['Comedy', 'Drama', 'Adventure'],
    overview: 'A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel\'s glorious years under an exceptional concierge.',
    director: 'Wes Anderson',
    cast: [
      { id: 55, name: 'Ralph Fiennes', character: 'M. Gustave' },
      { id: 56, name: 'Tony Revolori', character: 'Zero Moustafa' },
      { id: 57, name: 'Saoirse Ronan', character: 'Agatha' },
    ],
    runtime: 99,
    language: 'English',
    country: 'Germany',
    imdbRating: 8.1,
    rottenTomatoes: 91,
    posterColor: 'linear-gradient(145deg, #2d0d3d, #5a1a7a, #8b2fc9)',
    accentColor: '#EC4899',
    backdropColor: 'linear-gradient(135deg, #2d0d3d 0%, #5a1a7a 50%, #8b2fc9 100%)',
    status: 'watched',
    userRating: 8,
    watchedDate: '2024-07-20',
    isFavorite: false,
    isInWatchlist: false,
    decade: 2010,
    popularity: 83,
    budget: 25000000,
    boxOffice: 174800000,
    streamingOn: ['Disney+'],
  },
  {
    id: 21,
    title: 'Mad Max: Fury Road',
    year: 2015,
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    overview: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.',
    director: 'George Miller',
    cast: [
      { id: 58, name: 'Tom Hardy', character: 'Max Rockatansky' },
      { id: 59, name: 'Charlize Theron', character: 'Imperator Furiosa' },
    ],
    runtime: 120,
    language: 'English',
    country: 'Australia',
    imdbRating: 8.1,
    rottenTomatoes: 97,
    posterColor: 'linear-gradient(145deg, #3d1a00, #8b3a00, #c05a00)',
    accentColor: '#F97316',
    backdropColor: 'linear-gradient(135deg, #3d1a00 0%, #8b3a00 50%, #c05a00 100%)',
    status: 'watched',
    userRating: 9,
    watchedDate: '2024-08-05',
    isFavorite: true,
    isInWatchlist: false,
    decade: 2010,
    popularity: 91,
    awards: ['Academy Award for Best Film Editing', 'Best Production Design', 'Best Costume Design'],
    budget: 150000000,
    boxOffice: 375400000,
    streamingOn: ['HBO Max'],
  },
  {
    id: 22,
    title: 'Hereditary',
    year: 2018,
    genre: ['Horror', 'Drama', 'Mystery'],
    overview: 'A grieving family is haunted by tragic and disturbing occurrences.',
    director: 'Ari Aster',
    cast: [
      { id: 60, name: 'Toni Collette', character: 'Annie Graham' },
      { id: 61, name: 'Gabriel Byrne', character: 'Steve Graham' },
      { id: 62, name: 'Alex Wolff', character: 'Peter Graham' },
    ],
    runtime: 127,
    language: 'English',
    country: 'USA',
    imdbRating: 7.3,
    rottenTomatoes: 90,
    posterColor: 'linear-gradient(145deg, #0a0a0a, #1a0d1a, #2d0d2d)',
    accentColor: '#C084FC',
    backdropColor: 'linear-gradient(135deg, #0a0a0a 0%, #1a0d1a 50%, #2d0d2d 100%)',
    status: 'watched',
    userRating: 7,
    watchedDate: '2024-10-31',
    isFavorite: false,
    isInWatchlist: false,
    decade: 2010,
    popularity: 79,
    budget: 10000000,
    boxOffice: 44000000,
    streamingOn: ['Amazon Prime'],
  },
  {
    id: 23,
    title: 'Joker',
    year: 2019,
    genre: ['Crime', 'Drama', 'Thriller'],
    overview: 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.',
    director: 'Todd Phillips',
    cast: [
      { id: 63, name: 'Joaquin Phoenix', character: 'Arthur Fleck / Joker' },
      { id: 64, name: 'Robert De Niro', character: 'Murray Franklin' },
    ],
    runtime: 122,
    language: 'English',
    country: 'USA',
    imdbRating: 8.4,
    rottenTomatoes: 69,
    posterColor: 'linear-gradient(145deg, #1a0500, #3d0f00, #6b1a00)',
    accentColor: '#F97316',
    backdropColor: 'linear-gradient(135deg, #1a0500 0%, #3d0f00 50%, #6b1a00 100%)',
    status: 'watched',
    userRating: 8,
    watchedDate: '2024-09-10',
    isFavorite: false,
    isInWatchlist: false,
    decade: 2010,
    popularity: 94,
    budget: 55000000,
    boxOffice: 1079300000,
    streamingOn: ['HBO Max'],
  },
  {
    id: 24,
    title: 'Moonlight',
    year: 2016,
    genre: ['Drama'],
    overview: 'A young African-American man grapples with his identity and sexuality while experiencing the everyday struggles of childhood, adolescence, and burgeoning adulthood.',
    director: 'Barry Jenkins',
    cast: [
      { id: 65, name: 'Mahershala Ali', character: 'Juan' },
      { id: 66, name: 'Naomie Harris', character: 'Paula' },
      { id: 67, name: 'Trevante Rhodes', character: 'Chiron (adult)' },
    ],
    runtime: 111,
    language: 'English',
    country: 'USA',
    imdbRating: 7.4,
    rottenTomatoes: 98,
    posterColor: 'linear-gradient(145deg, #001a3d, #003a7a, #005ab3)',
    accentColor: '#60A5FA',
    backdropColor: 'linear-gradient(135deg, #001a3d 0%, #003a7a 50%, #005ab3 100%)',
    status: 'plan_to_watch',
    isFavorite: false,
    isInWatchlist: true,
    watchlistPriority: 4,
    decade: 2010,
    popularity: 76,
    budget: 4000000,
    boxOffice: 65300000,
    streamingOn: ['Paramount+'],
  },
  {
    id: 25,
    title: 'Prisoners',
    year: 2013,
    genre: ['Crime', 'Drama', 'Thriller'],
    overview: 'When Keller Dover\'s daughter and her friend go missing, he takes matters into his own hands as the police pursue multiple leads and the pressure mounts.',
    director: 'Denis Villeneuve',
    cast: [
      { id: 68, name: 'Hugh Jackman', character: 'Keller Dover' },
      { id: 69, name: 'Jake Gyllenhaal', character: 'Detective Loki' },
      { id: 70, name: 'Viola Davis', character: 'Nancy Birch' },
    ],
    runtime: 153,
    language: 'English',
    country: 'USA',
    imdbRating: 8.1,
    rottenTomatoes: 81,
    posterColor: 'linear-gradient(145deg, #0d0d1a, #1a1a3e, #2d2d6b)',
    accentColor: '#94A3B8',
    backdropColor: 'linear-gradient(135deg, #0d0d1a 0%, #1a1a3e 50%, #2d2d6b 100%)',
    status: 'watched',
    userRating: 9,
    watchedDate: '2024-05-01',
    isFavorite: true,
    isInWatchlist: false,
    decade: 2010,
    popularity: 88,
    budget: 46000000,
    boxOffice: 122200000,
    streamingOn: ['Netflix'],
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'r1',
    movieId: 1,
    userId: 'user-1',
    userName: 'Alex Cinema',
    rating: 9,
    title: 'A masterpiece of layers within layers',
    content: 'Nolan has crafted something truly extraordinary here. The dream-within-a-dream concept is executed flawlessly, and DiCaprio delivers one of his finest performances. The Hans Zimmer score alone is worth the price of admission. Every rewatch reveals new details and hidden meanings. A true modern classic.',
    likes: 42,
    isLiked: false,
    createdAt: '2024-03-16',
    containsSpoilers: false,
    tags: ['mindblowing', 'rewatch-worthy', 'masterpiece'],
  },
  {
    id: 'r2',
    movieId: 2,
    userId: 'user-1',
    userName: 'Alex Cinema',
    rating: 10,
    title: "Heath Ledger's immortal performance",
    content: "The Dark Knight transcends the superhero genre entirely. This is pure cinema. Heath Ledger's Joker is one of the greatest performances in film history - terrifying, funny, and utterly unpredictable. The film's moral philosophy around chaos vs. order still resonates deeply. A true 10/10.",
    likes: 87,
    isLiked: false,
    createdAt: '2024-02-11',
    containsSpoilers: true,
    tags: ['heath-ledger', 'best-villain', 'superhero-peak'],
  },
  {
    id: 'r3',
    movieId: 7,
    userId: 'user-1',
    userName: 'Alex Cinema',
    rating: 10,
    title: 'An offer cinema cannot refuse',
    content: "Coppola's masterwork is the gold standard against which all crime films are measured. Brando's performance as Vito Corleone is mythical. Every scene is perfectly composed. The family dynamics, the corruption of power, the inevitability of violence - all captured with operatic grandeur. Cinema doesn't get better than this.",
    likes: 63,
    isLiked: false,
    createdAt: '2024-01-06',
    containsSpoilers: false,
    tags: ['classic', 'must-watch', 'perfect-film'],
  },
];

export const MONTHLY_ACTIVITY = [
  { month: 'Jan', watched: 8, reviewed: 3, hours: 14 },
  { month: 'Feb', watched: 12, reviewed: 5, hours: 22 },
  { month: 'Mar', watched: 10, reviewed: 4, hours: 18 },
  { month: 'Apr', watched: 15, reviewed: 7, hours: 28 },
  { month: 'May', watched: 9, reviewed: 3, hours: 16 },
  { month: 'Jun', watched: 11, reviewed: 6, hours: 20 },
  { month: 'Jul', watched: 7, reviewed: 2, hours: 13 },
  { month: 'Aug', watched: 14, reviewed: 8, hours: 26 },
  { month: 'Sep', watched: 16, reviewed: 5, hours: 30 },
  { month: 'Oct', watched: 13, reviewed: 4, hours: 24 },
  { month: 'Nov', watched: 18, reviewed: 9, hours: 33 },
  { month: 'Dec', watched: 20, reviewed: 11, hours: 38 },
];

export const GENRE_DISTRIBUTION = [
  { genre: 'Sci-Fi', count: 45, percentage: 28, color: '#3B82F6' },
  { genre: 'Drama', count: 38, percentage: 24, color: '#8B5CF6' },
  { genre: 'Action', count: 30, percentage: 19, color: '#EF4444' },
  { genre: 'Thriller', count: 20, percentage: 13, color: '#F97316' },
  { genre: 'Crime', count: 15, percentage: 9, color: '#F59E0B' },
  { genre: 'Horror', count: 12, percentage: 7, color: '#10B981' },
];

export const ALL_GENRES = [
  'Action', 'Adventure', 'Animation', 'Biography', 'Comedy', 'Crime',
  'Documentary', 'Drama', 'Fantasy', 'Horror', 'History', 'Music',
  'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'Western',
];
