import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../api/client';

interface ApiMovie { id: string; title: string; year: number | null; genres: string[]; vote_average: number | null }
interface Profile { id: string; username: string; name: string; bio?: string; location?: string; avatar_url?: string; is_private: boolean; is_owner: boolean; restricted: boolean; watched: ApiMovie[]; favorites: ApiMovie[]; rated: ApiMovie[] }

export default function PublicProfilePage() {
  const { username = '' } = useParams(); const [profile, setProfile] = useState<Profile | null>(null); const [error, setError] = useState('');
  useEffect(() => { setProfile(null); setError(''); api.get<Profile>(`/api/users/${encodeURIComponent(username)}`).then(setProfile).catch((reason: Error) => setError(reason.message)); }, [username]);
  if (error) return <main className="min-h-screen grid place-items-center p-4" style={{ background: 'var(--bg)' }}><div className="glass-card p-8 text-center"><h1 className="text-xl font-bold" style={{ color: 'var(--text)' }}>Profile unavailable</h1><p className="mt-2" style={{ color: 'var(--text-muted)' }}>{error}</p></div></main>;
  if (!profile) return <main className="min-h-screen grid place-items-center" style={{ background: 'var(--bg)', color: 'var(--text-muted)' }}>Loading profile…</main>;
  return <main className="min-h-screen px-4 py-12" style={{ background: 'var(--bg)' }}><div className="max-w-5xl mx-auto space-y-6"><section className="glass-card p-7 flex gap-5 items-center"><div className="w-20 h-20 rounded-2xl grid place-items-center text-2xl font-black" style={{ background: 'var(--accent)', color: '#000' }}>{profile.name.slice(0, 2).toUpperCase()}</div><div><h1 className="text-3xl font-black" style={{ color: 'var(--text)' }}>{profile.name}</h1><p style={{ color: 'var(--accent)' }}>@{profile.username}</p>{profile.restricted ? <p className="mt-3" style={{ color: 'var(--text-muted)' }}>🔒 This account is private.</p> : <><p className="mt-2" style={{ color: 'var(--text-muted)' }}>{profile.bio}</p>{profile.location && <p className="text-sm mt-1" style={{ color: 'var(--text-muted)' }}>📍 {profile.location}</p>}</>}</div></section>{!profile.restricted && <section><div className="flex items-end justify-between mb-4"><div><h2 className="text-xl font-bold" style={{ color: 'var(--text)' }}>Watched movies</h2><p className="text-sm" style={{ color: 'var(--text-muted)' }}>{profile.watched.length} watched</p></div></div>{profile.watched.length ? <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-3">{profile.watched.map((movie) => <Link key={movie.id} to="/login" className="glass-card p-4 no-underline"><h3 className="font-bold" style={{ color: 'var(--text)' }}>{movie.title}</h3><p className="text-sm" style={{ color: 'var(--text-muted)' }}>{movie.year} · ⭐ {movie.vote_average ?? '—'}</p></Link>)}</div> : <div className="glass-card p-8 text-center" style={{ color: 'var(--text-muted)' }}>No watched movies yet.</div>}</section>}</div></main>;
}
